name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    strategy:
      fail-fast: false
      matrix:
        include:
          - pair:
              elixir: 1.12
              otp: 22.3
          - pair:
              elixir: 1.17
              otp: 27

    steps:
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}

      - uses: actions/checkout@v4

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
